/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AreaManagersRouteImport } from './routes/area-managers'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as NotAuthorisedRouteImport } from './routes/not-authorised'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProvincesRouteImport } from './routes/provinces'
import { Route as SalesRepsRouteImport } from './routes/sales-reps'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as TerritoriesRouteImport } from './routes/territories'
import { Route as TerritoryAssignmentsRouteImport } from './routes/territory-assignments'
import { Route as RecordsEntityIdRouteImport } from './routes/records.$entity.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaManagersRoute = AreaManagersRouteImport.update({
  id: '/area-managers',
  path: '/area-managers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const NotAuthorisedRoute = NotAuthorisedRouteImport.update({
  id: '/not-authorised',
  path: '/not-authorised',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvincesRoute = ProvincesRouteImport.update({
  id: '/provinces',
  path: '/provinces',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRepsRoute = SalesRepsRouteImport.update({
  id: '/sales-reps',
  path: '/sales-reps',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoriesRoute = TerritoriesRouteImport.update({
  id: '/territories',
  path: '/territories',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoryAssignmentsRoute = TerritoryAssignmentsRouteImport.update({
  id: '/territory-assignments',
  path: '/territory-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsEntityIdRoute = RecordsEntityIdRouteImport.update({
  id: '/records/$entity/$id',
  path: '/records/$entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/area-managers': typeof AreaManagersRoute
  '/inventory': typeof InventoryRoute
  '/not-authorised': typeof NotAuthorisedRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/provinces': typeof ProvincesRoute
  '/sales-reps': typeof SalesRepsRoute
  '/shops': typeof ShopsRoute
  '/territories': typeof TerritoriesRoute
  '/territory-assignments': typeof TerritoryAssignmentsRoute
  '/records/$entity/$id': typeof RecordsEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/area-managers': typeof AreaManagersRoute
  '/inventory': typeof InventoryRoute
  '/not-authorised': typeof NotAuthorisedRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/provinces': typeof ProvincesRoute
  '/sales-reps': typeof SalesRepsRoute
  '/shops': typeof ShopsRoute
  '/territories': typeof TerritoriesRoute
  '/territory-assignments': typeof TerritoryAssignmentsRoute
  '/records/$entity/$id': typeof RecordsEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/area-managers': typeof AreaManagersRoute
  '/inventory': typeof InventoryRoute
  '/not-authorised': typeof NotAuthorisedRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/provinces': typeof ProvincesRoute
  '/sales-reps': typeof SalesRepsRoute
  '/shops': typeof ShopsRoute
  '/territories': typeof TerritoriesRoute
  '/territory-assignments': typeof TerritoryAssignmentsRoute
  '/records/$entity/$id': typeof RecordsEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/area-managers'
    | '/inventory'
    | '/not-authorised'
    | '/orders'
    | '/products'
    | '/provinces'
    | '/sales-reps'
    | '/shops'
    | '/territories'
    | '/territory-assignments'
    | '/records/$entity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencies'
    | '/area-managers'
    | '/inventory'
    | '/not-authorised'
    | '/orders'
    | '/products'
    | '/provinces'
    | '/sales-reps'
    | '/shops'
    | '/territories'
    | '/territory-assignments'
    | '/records/$entity/$id'
  id:
    | '__root__'
    | '/'
    | '/agencies'
    | '/area-managers'
    | '/inventory'
    | '/not-authorised'
    | '/orders'
    | '/products'
    | '/provinces'
    | '/sales-reps'
    | '/shops'
    | '/territories'
    | '/territory-assignments'
    | '/records/$entity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciesRoute: typeof AgenciesRoute
  AreaManagersRoute: typeof AreaManagersRoute
  InventoryRoute: typeof InventoryRoute
  NotAuthorisedRoute: typeof NotAuthorisedRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ProvincesRoute: typeof ProvincesRoute
  SalesRepsRoute: typeof SalesRepsRoute
  ShopsRoute: typeof ShopsRoute
  TerritoriesRoute: typeof TerritoriesRoute
  TerritoryAssignmentsRoute: typeof TerritoryAssignmentsRoute
  RecordsEntityIdRoute: typeof RecordsEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-managers': {
      id: '/area-managers'
      path: '/area-managers'
      fullPath: '/area-managers'
      preLoaderRoute: typeof AreaManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-authorised': {
      id: '/not-authorised'
      path: '/not-authorised'
      fullPath: '/not-authorised'
      preLoaderRoute: typeof NotAuthorisedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provinces': {
      id: '/provinces'
      path: '/provinces'
      fullPath: '/provinces'
      preLoaderRoute: typeof ProvincesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-reps': {
      id: '/sales-reps'
      path: '/sales-reps'
      fullPath: '/sales-reps'
      preLoaderRoute: typeof SalesRepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territories': {
      id: '/territories'
      path: '/territories'
      fullPath: '/territories'
      preLoaderRoute: typeof TerritoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territory-assignments': {
      id: '/territory-assignments'
      path: '/territory-assignments'
      fullPath: '/territory-assignments'
      preLoaderRoute: typeof TerritoryAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$entity/$id': {
      id: '/records/$entity/$id'
      path: '/records/$entity/$id'
      fullPath: '/records/$entity/$id'
      preLoaderRoute: typeof RecordsEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciesRoute: AgenciesRoute,
  AreaManagersRoute: AreaManagersRoute,
  InventoryRoute: InventoryRoute,
  NotAuthorisedRoute: NotAuthorisedRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ProvincesRoute: ProvincesRoute,
  SalesRepsRoute: SalesRepsRoute,
  ShopsRoute: ShopsRoute,
  TerritoriesRoute: TerritoriesRoute,
  TerritoryAssignmentsRoute: TerritoryAssignmentsRoute,
  RecordsEntityIdRoute: RecordsEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
